api:
  url: http://api.stackexchange.com/2.2/search?site=stackoverflow
  filter: "!9Z(-x-PxR" #http://api.stackexchange.com/docs/create-filter#include=.total%3B.page_size&unsafe=false&filter=default&run=true